import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const homePageVideoSource = "https://www.youtube.com/embed/hgBfkFjF2v8?autohide=0&autoplay=1&controls=0&loop=0";
  // const homePageVideoSource = "https://www.youtube.com/embed/hgBfkFjF2v8?autohide=1&autoplay=0&controls=0&enablejsapi=1&iv_load_policy=3&loop=0&modestbranding=1&playsinline=1&rel=0&showinfo=0&wmode=opaque";
  // const homePageVideoSource = "https://www.youtube.com/embed/X1nxTjVDYdQ";
  return (
    <div className={styles.container}>
      <Head>
        <title>TFP Models</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <iframe
          width={320}
          height={320}
          src={homePageVideoSource}
          autoPlay
          // loop
        >
        </iframe>
      </div>
    </div>
  )
}
